
NET_DISCOVERY_PORT = 4000
NET_EVENT_PROVIDER_PORT = 4001

DISCOVERY_SERVICE_CODE = 0x02

CLOSE_CONNECTION_CODE = 'CLOSE'
USER_ACK_CODE = 'ACK'
SMART_GAME_PLATFORM_SENSORS_SAMPLE_CODE = 'SGP_STATUS'
SMARTBALL_SENSORS_SAMPLE_CODE = 'SB_STATUS'
SMARTPOLE_SENSORS_SAMPLE_CODE = 'SP_STATUS'
MAIN_SMART_RACKET_STATUS_SAMPLE_CODE = 'MSR_STATUS'
